### ISSUE TITLE
Function to get the current waker in an async fn

### ISSUE THREAD

**Issue by jjl** [smol-rs/futures-lite#8]
Not sure about the name, but I just found a use for this and it's incredibly small. Maybe you have a better idea for a name?

```
pub async fn waker() -> Waker {
    future::poll_fn(|c| Poll::Ready(c.waker().clone())).await
}
```

**Comment by jjl** [comment]
slightly more contentious bonus:

```
pub async fn delay() {
    let mut done = false;
    future::poll_fn(|_| {
        if done {
            Poll::Ready(())
        } else {
            done = true;
            Poll::Pending
        }
    }).await
}
```

**Comment by stjepang** [comment]
I've wanted `waker()` before, more than once :) I think it's useful! The name sounds good to me. Some other ideas: `get_waker()`, `current_waker()`. Not sure if its possible, but perhaps it'd be worth changing the signature to return a `&Waker` rather than `Waker`.

Regarding `delay()`, I think that's same as `futures_lite::future::yield_now()`.

**Comment by jjl** [comment]
AIUI, yield_now() reschedules the current future? Delay is for when you don't want to do that (because you're messing with wakers)

**Comment by jjl** [comment]
I went and looked, and yes, that's the essential difference - with `delay`, we don't wake ourselves.

**Comment by jjl** [comment]
These have now made it into [futures-micro](https://github.com/irrustible/futures-micro) as 'waker' and 'sleep'. You might also like to steal `PollState`. Or you might find it offensive and decide not to :)

**Comment by notgull** [comment]
See [this comment](https://github.com/smol-rs/futures-lite/pull/58#issuecomment-1242047910). I don't think we should add this; it's a bit niche.
